### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by ghost** [ajmeese7/automatic-reactions#3]
Hi its possible to Add support for specific channels ?

**Comment by ajmeese7** [comment]
I'll look into it right now and get back to you

**Comment by RizwanS1** [comment]
You can also try doing it for specific message and adding a reaction by the person's id rather than mentioning them.

**Comment by ajmeese7** [comment]
@Piikachuu support for specific channels is now included. For any confusion check the new readme examples on how to use the command. Cheers!
