### ISSUE TITLE
Please I need this so much!!

### ISSUE THREAD

**Issue by karimawi** [ajmeese7/automatic-reactions#4]
Add a Command That Specifies a Channel Where Every Message That's Sent in it Will Get Reacts Whatever The User is, and add the option for more than one reaction like 7 or 10, I looked everywhere on the internet, can't find any code that works.

**Comment by ajmeese7** [comment]
Would you want that to be a command, or something you just add in the JSON config file? Because I could probably add an array of channels as a config option, then you could specify what emojis to react to messages if they are sent in that channel. That shouldn't be too difficult.

**Comment by karimawi** [comment]
Yeah, just add it in the json file
